# src/main/resources/application.yml 설정파일
spring:
  datasource:
    url: jdbc:mysql://mgs-mysql-0821.cw62tn0po7ui.ap-northeast-2.rds.amazonaws.com:3306/JENGA_DB
    username: jengauser
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.MariaDBDialect
        dialect: org.hibernate.dialect.MySQL5Dialect
logging.level:
  org.hibernate.sql: debug

