# src/main/resources/application.yml 설정파일
spring:
  config:
    activate:
      on-profile: common
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
# local, prod 공통 설정
server:
  port: 8080

---

spring:
  profiles:
    active: prod

---

spring:
  profiles:
    active: local
