spring:
  datasource:
    url: jdbc:mysql://mgs-mysql-0821.cw62tn0po7ui.ap-northeast-2.rds.amazonaws.com:3306/JENGA_DB
    username: jengauser
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        use_sql_comments: false
        hbm2ddl:
          auto: validate
logging:
  level:
    org.hibernate: error
